#1 Introducción


En el siguiente cuaderno obtenemos la matriz transpuesta de una matriz de números flotantes de manera secuencial utilizando solo procesador CPU.

El objetivo es comparar los tiempos de ejecución de ambas versiones (secuencial vs paralelismo) del algoritmo que obtiene la matriz transpuesta.

#2 Armado del ambiente

No son necesarios, ejecuciones previas del armado del ambiente.

#3 Desarrollo 

In [ ]:
#@title Parametros: { vertical-output: true, display-mode: "both" }
ordenMatriz =  5#@param {type:"number"}

from datetime import datetime
tiempo_total = datetime.now()

import numpy

# Definición de función que transforma el tiempo en  milisegundos 
tiempo_en_ms = lambda dt:(dt.days * 24 * 60 * 60 + dt.seconds) * 1000 + dt.microseconds / 1000.0

# CPU - Defino la memoria de las matrices en cpu.

try:
  matriz = numpy.random.random((ordenMatriz,ordenMatriz))
  matriz = matriz.astype(numpy.float32())
  matrizT = numpy.empty_like(matriz)

  tiempo_bucle = datetime.now()

  for i in range(0,ordenMatriz):
    for j in range(0,ordenMatriz):
      matrizT[j][i] = matriz[i][j]

  tiempo_bucle = datetime.now() - tiempo_bucle
  tiempo_total = datetime.now() - tiempo_total
  
  print("Matriz original: ")
  print(matriz)
  print("")
  print("Matriz transpuesta: ")
  print(matrizT)
  print("")
  print("Tiempo Total: ", tiempo_en_ms( tiempo_total ), "[ms]" )
  print("Tiempo bucle: ", tiempo_en_ms( tiempo_bucle ), "[ms]" )

except ValueError:
  print("se ingreso un orden (tamaño de la matriz) menor a 0")
  print("ingrese un orden mayor a 0")


Matriz original: 
[[0.60751855 0.08994103 0.53095305 0.5923071  0.44280097]
 [0.02026618 0.20784345 0.78383785 0.95131385 0.9146255 ]
 [0.47539505 0.6447987  0.68640614 0.9715737  0.70004684]
 [0.3987849  0.4300021  0.9473704  0.7168067  0.22456126]
 [0.7636829  0.34643552 0.54124856 0.09217121 0.44175905]]

Matriz transpuesta: 
[[0.60751855 0.02026618 0.47539505 0.3987849  0.7636829 ]
 [0.08994103 0.20784345 0.6447987  0.4300021  0.34643552]
 [0.53095305 0.78383785 0.68640614 0.9473704  0.54124856]
 [0.5923071  0.95131385 0.9715737  0.7168067  0.09217121]
 [0.44280097 0.9146255  0.70004684 0.22456126 0.44175905]]

Tiempo Total:  0.289 [ms]


#4 Tabla de pasos de ejecución del programa

 Procesador | Funciòn | Detalle
------------|---------|----------
CPU      |  @param                | Lectura del tamaño de la matriz desde colab.
CPU      |  import                | Importa los módulos para funcionar.
CPU      |  datetime.now()        | Toma el tiempo actual.
CPU      |  numpy.random.randn( ordenMatriz ) | Inicializa las matrices
CPU      |  for                   | transpongo la matriz 
CPU      |  print()               | Informo los resultados.

#5 Conclusiones

#6 Bibliografia

[1] MARKDOWN SYNTAX Colab:[PDF](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/markdown-cheatsheet-online.pdf)

[2] Introducción a Python: [pagina colab](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/Python_Basico.ipynb)