#1 Introducción


En el siguiente cuaderno se realiza el algoritmo que obtiene la matriz transpuesta de una matriz (su orden se ingresa por parametro) de números flotantes de manera secuencial utilizando el procesador CPU.

El algoritmo de este cuadernos se basa en, valga la redundancia, del algortimo para transponer una matriz proveniente del algebra lineal[3]

El objetivo es comparar los tiempos de ejecución de ambas versiones del algoritmo que obtiene la matriz transpuesta, utilizando el lenguaje python [2] en la plataforma colab [1]

#2 Armado del ambiente

No son necesarios, ejecuciones previas del armado del ambiente.

#3 Desarrollo 

In [ ]:
#@title Parametros: { vertical-output: true, display-mode: "both" }
ordenMatriz =  5#@param {type:"number"}

from datetime import datetime
tiempo_total = datetime.now()

import numpy

# Definición de función que transforma el tiempo en  milisegundos 
tiempo_en_ms = lambda dt:(dt.days * 24 * 60 * 60 + dt.seconds) * 1000 + dt.microseconds / 1000.0

# CPU - Defino la memoria de las matrices en cpu.

try:
  matriz = numpy.random.random((ordenMatriz,ordenMatriz))
  matriz = matriz.astype(numpy.float32())
  matrizT = numpy.empty_like(matriz)

  tiempo_bucle = datetime.now()

  for i in range(0,ordenMatriz):
    for j in range(0,ordenMatriz):
      matrizT[j][i] = matriz[i][j]

  tiempo_bucle = datetime.now() - tiempo_bucle
  tiempo_total = datetime.now() - tiempo_total
  
  print("Matriz original: ")
  print(matriz)
  print("")
  print("Matriz transpuesta: ")
  print(matrizT)
  print("")
  print("Tiempo Total: ", tiempo_en_ms( tiempo_total ), "[ms]" )
  print("Tiempo bucle: ", tiempo_en_ms( tiempo_bucle ), "[ms]" )

except ValueError:
  print("se ingreso un orden (tamaño de la matriz) menor a 0")
  print("ingrese un orden mayor a 0")


Matriz original: 
[[0.60751855 0.08994103 0.53095305 0.5923071  0.44280097]
 [0.02026618 0.20784345 0.78383785 0.95131385 0.9146255 ]
 [0.47539505 0.6447987  0.68640614 0.9715737  0.70004684]
 [0.3987849  0.4300021  0.9473704  0.7168067  0.22456126]
 [0.7636829  0.34643552 0.54124856 0.09217121 0.44175905]]

Matriz transpuesta: 
[[0.60751855 0.02026618 0.47539505 0.3987849  0.7636829 ]
 [0.08994103 0.20784345 0.6447987  0.4300021  0.34643552]
 [0.53095305 0.78383785 0.68640614 0.9473704  0.54124856]
 [0.5923071  0.95131385 0.9715737  0.7168067  0.09217121]
 [0.44280097 0.9146255  0.70004684 0.22456126 0.44175905]]

Tiempo Total:  0.289 [ms]


#4 Tabla de pasos de ejecución del programa

 Procesador | Funciòn | Detalle
------------|---------|----------
CPU      |  @param                | Lectura del tamaño de la matriz desde colab.
CPU      |  import                | Importa los módulos para funcionar.
CPU      |  datetime.now()        | Toma el tiempo actual.
CPU      |  numpy.random.randn( ordenMatriz ) | Inicializa las matrices
CPU      | datetime.now()         | toma el tiempo del bucle
CPU      |  for                   | transpongo la matriz 
CPU      |  print()               | Informo los resultados.

#5 Conclusiones

En este ejercicio que se basa en el algortimo que obtiene la matriz transpuesta de una matriz, los tiempos de ejecución resultaron más eficientes utilizando paralelismo utilizando el GPGPU porque al ser un algoritmo donde se puede mover grandes cantidades de datos ya que los tiempos de ejecución  son pequeños en comparación con la versión secuencial porque evitamos cualquier tipo de bucles, por la enorme cantidad de hilos que nos ofrece la GPU que nos permiten evitar estos bucles ya que podemos acceder de manera directa a los datos correspondientes.

Para poder sacar estas conclusiones tome 20 muestras del algoritmo en la version secuencial (CPU) y la versión con paralelismo (CPU-GPU) con un número de elementos igual a 100 y obtuve los siguientes promedios:

Promedio de tiempo ejercicio 2 secuencial: 12.224,4 ms

Promedio de tiempo de Bucle ejercicio 2: 11.497,4 ms

Promedio de tiempo CPU ejercicio 2 paralelismo: 2.407 ms 

Promedio de tiempo GPU ejercicio 2 paralelismo: 0,2676 ms


Como vemos en los resultados obtenidos, el tiempo total(CPU) en la versión con paralelismo (GPGPU) es menor al tiempo equivalente que es el tiempo de CPU, en la versión secuencial.

Por este motivo puedo decir que en los ejercicios donde tenemos que mover grandes cantidades de datos, utilizar paralelismo con (GPGPU) es más optimo porque como mencione anteriormente nos permite acceder de manera directa a los datos correspondientes y nos permite evitar el uso de bucles permitiendonos de esta manera ahorrar mucho tiempo de ejecución.

Para continuar este ejercicio tanto en la versión secuencial como en la versión con paralelismo se podría hacer que hagamos 2 movimientos de datos al mismo tiempo y ahorrar la mitad del tiempo, es decir, por ejemplo cuando se va a copiar un valor de la matriz de la posicion [ i ][ j ] a la posición [ j ][ i ],antes de hacer esto, se podria copiar el valor de la posicion [ j ][ i ] en una variable auxiliar y copiar el valor en la posicion [ i ][ j ] luego de que el valor de esta posición haya sido copiado en la posición [ j ][ i ], para poder asi, reducir el tiempo de ejecución a la mitad.

#6 Bibliografia

[1] MARKDOWN SYNTAX Colab:[PDF](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/markdown-cheatsheet-online.pdf)

[2] Introducción a Python: [pagina colab](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/Python_Basico.ipynb)

[3] Función de transponer matriz: [WEB](https://es.wikipedia.org/wiki/Matriz_transpuesta)