#1 Introducción


En el siguiente cuaderno obtenemos la matriz transpuesta de una matriz de números flotantes de manera secuencial utilizando solo procesador CPU.

El objetivo es comparar los tiempos de ejecución de ambas versiones (secuencial vs paralelismo) del algoritmo que obtiene la matriz transpuesta.

#2 Armado del ambiente

No son necesarios, ejecuciones previas del armado del ambiente.

#3 Desarrollo 

In [38]:
#@title Parametros: { vertical-output: true, display-mode: "both" }
ordenMatriz =  3#@param {type:"number"}
import numpy

# CPU - Defino la memoria de las matrices en cpu.
matriz = numpy.random.random((ordenMatriz,ordenMatriz))
matriz = matriz.astype(numpy.float32())
matrizT = numpy.empty_like(matriz)


for i in range(0,ordenMatriz):
  for j in range(0,ordenMatriz):
    matrizT[j][i] = matriz[i][j]

print("Matriz original: ")
print(matriz)
print("Matriz transpuesta: ")
print(matrizT)

Matriz original: 
[[0.34585702 0.6265789  0.35849816]
 [0.98542726 0.9923011  0.6252269 ]
 [0.03927162 0.41529363 0.54600155]]
Matriz transpuesta: 
[[0.34585702 0.98542726 0.03927162]
 [0.6265789  0.9923011  0.41529363]
 [0.35849816 0.6252269  0.54600155]]


#4 Tabla de pasos de ejecución del programa

 Procesador | Funciòn | Detalle
------------|---------|----------
CPU      |  @param                | Lectura del tamaño de la matriz desde colab.
CPU      |  import                | Importa los módulos para funcionar.
CPU      |  datetime.now()        | Toma el tiempo actual.
CPU      |  numpy.random.randn( ordenMatriz ) | Inicializa las matrices
CPU      |  for                   | transpongo la matriz 
CPU      |  print()               | Informo los resultados.

#5 Conclusiones

#6 Bibliografia

[1] MARKDOWN SYNTAX Colab:[PDF](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/markdown-cheatsheet-online.pdf)

[2] Introducción a Python: [pagina colab](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/Python_Basico.ipynb)